# Generated by Django 4.0.4 on 2022-06-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hocphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenhocphan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Taikhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tudien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thuatngu', models.CharField(max_length=200)),
                ('dinhnghia', models.CharField(max_length=200)),
                ('hocphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hocphan')),
            ],
        ),
        migrations.AddField(
            model_name='hocphan',
            name='taikhoan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.taikhoan'),
        ),
    ]
