# Generated by Django 4.0.4 on 2022-06-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocphan',
            name='mota',
            field=models.CharField(default='newdatabase', max_length=200),
            preserve_default=False,
        ),
    ]
