# Generated by Django 4.0.4 on 2022-06-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hocphan_mota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocphan',
            name='taikhoan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.taikhoan'),
        ),
        migrations.AlterField(
            model_name='tudien',
            name='hocphan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.hocphan'),
        ),
    ]
